// ============================ KAJIAN YURIDIS ============================
const kajian = [
  ...kop(),
  center("**KAJIAN YURIDIS**", { run: { size: 26 } }),
  center("**PEMBERESAN HAK KEPERDATAAN ATAS EKS HGU NO. 2/SEI TAMPA**"),
  center("**MELALUI PENJUALAN BENDA DAN CESSIE HAK TAGIH,**"),
  center("**SERTA PENGAMANAN PELAKSANAAN DI LAPANGAN**", { after: 120 }),
  center("Kepailitan PT Rata Makmur (Dalam Pailit), Putusan No. 33/Pdt.Sus-PKPU/2022/PN Niaga Mdn", { after: 60 }),
  center("Lampiran Telaahan Staf tanggal 29 September 2026", { after: 240 }),

  heading("I.\tPERTANYAAN YANG DIJAWAB"),
  item("1.", "Hak apa saja yang masih dapat diuangkan dari eks HGU No. 2/Sei Tampa, dan bagaimana langkah penjualan bangunan serta pengalihan (cessie) hak tagihnya?"),
  item("2.", "Apa dasar hukum dan analisis yuridis atas setiap langkah tersebut?"),
  item("3.", "Bagaimana mengamankan pelaksanaan dari gangguan oknum preman di lokasi?"),
  item("4.", "Apakah Kurator dapat menjalankan pemberesan tanpa harus turun langsung ke lokasi?"),

  heading("II.\tJAWABAN SINGKAT"),
  item("1.", "Yang dapat diuangkan bukan tanahnya, melainkan: (a) bangunan dan benda milik PT Rata Makmur di atas tanah; (b) hak atas ganti rugi atas bangunan, tanaman, dan benda yang masih diperlukan untuk pengusahaan tanah; dan (c) hak menagih hasil kebun sejak 10 April 2023. Bangunan dan benda **dijual** (jual beli benda), sedangkan hak atas ganti rugi dan hak menagih hasil kebun **dialihkan dengan cessie** (Pasal 613 KUHPerdata). Keduanya paling efektif dijual sebagai satu paket kepada pemohon HGU baru, dengan izin Hakim Pengawas."),
  item("2.", "Dasar kewenangannya adalah Pasal 16, 69, dan 185 UU 37/2004. Dasar keberadaan haknya adalah Pasal 18 dan Pasal 4 ayat (4) PP 40/1996 serta asas pemisahan horizontal. Tata cara cessie tunduk pada Pasal 613 dan Pasal 1533–1535 KUHPerdata."),
  item("3.", "Pengamanan dilakukan lewat jalur resmi: penyegelan oleh juru sita dengan saksi pemerintah daerah (Pasal 99 UU 37/2004), permohonan pengamanan kepada Polres Langkat, pelibatan pemerintah desa dan kecamatan, serta protokol kunjungan yang ketat. Kurator tidak boleh bernegosiasi atau membayar apa pun kepada oknum di lapangan."),
  item("4.", "**Sebagian besar bisa, tetapi tidak seluruhnya.** Inventarisasi, penilaian, dan penguasaan fisik dapat dijalankan melalui juru sita, KJPP, surveyor BPN, citra satelit, dan pembeli. Penyerahan dapat dilakukan secara yuridis tanpa serah terima fisik. Namun, tanggung jawab tetap pada Kurator (Pasal 72 UU 37/2004). Karena itu, Kurator tetap perlu hadir paling sedikit sekali dalam kegiatan resmi yang dikawal aparat, atau sekurang-kurangnya memastikan setiap kegiatan lapangan dituangkan dalam berita acara pejabat yang berwenang."),

  heading("III.\tKERANGKA HUKUM"),
  sub("A. Kepailitan"),
  item("1.", "**Pasal 21 UU 37/2004:** harta pailit meliputi seluruh kekayaan Debitor pada saat putusan diucapkan dan segala sesuatu yang diperoleh selama kepailitan."),
  item("2.", "**Pasal 16 ayat (1) dan Pasal 69 ayat (1):** Kurator berwenang melaksanakan pengurusan dan pemberesan sejak putusan diucapkan."),
  item("3.", "**Pasal 98 dan 99:** Kurator wajib mengamankan harta pailit dan dapat meminta penyegelan melalui Hakim Pengawas, yang dilaksanakan juru sita di tempat harta berada dengan dihadiri dua saksi, salah satunya wakil pemerintah daerah setempat."),
  item("4.", "**Pasal 185:** (1) benda dijual di muka umum; (2) bila penjualan di muka umum tidak tercapai, dapat dijual di bawah tangan dengan izin Hakim Pengawas; (3) benda yang tidak segera atau sama sekali tidak dapat dibereskan, tindakannya diputuskan Kurator dengan izin Hakim Pengawas."),
  item("5.", "**Pasal 72:** Kurator bertanggung jawab atas kesalahan atau kelalaiannya yang merugikan harta pailit."),
  item("6.", "**Pasal 93, 110, dan 121:** Debitor wajib memberikan keterangan dan bekerja sama. Bila tidak, atas usul Hakim Pengawas atau permintaan Kurator, Pengadilan dapat memerintahkan penahanan Debitor."),
  sub("B. Pertanahan"),
  item("1.", "**Pasal 34 huruf a UUPA jo. Pasal 17 PP 40/1996:** HGU hapus karena jangka waktunya berakhir, dan tanahnya menjadi tanah negara."),
  item("2.", "**Pasal 18 PP 40/1996:** bekas pemegang HGU wajib membongkar bangunan dan benda serta menyerahkan tanah dan tanaman kepada negara. Bila bangunan, tanaman, dan benda itu masih diperlukan untuk melangsungkan atau memulihkan pengusahaan tanah, bekas pemegang hak diberi ganti rugi. Pembongkaran menjadi beban bekas pemegang hak."),
  item("3.", "**Pasal 4 ayat (4) PP 40/1996 dan Penjelasannya:** bila di atas tanah yang akan diberikan HGU terdapat tanaman atau bangunan milik pihak lain yang keberadaannya sah, pemiliknya diberi ganti kerugian yang dibebankan kepada pemegang HGU baru."),
  item("4.", "**Asas pemisahan horizontal** (Pasal 5 UUPA, yang bersumber dari hukum adat): bangunan dan tanaman bukan bagian dari tanah, sehingga tetap milik PT Rata Makmur walaupun tanahnya kembali kepada negara."),
  item("5.", "**PP 18/2021**, termasuk Pasal 22 tentang penataan kembali tanah negara bekas hak dan prioritas bekas pemegang hak."),
  sub("C. Hukum perdata"),
  item("1.", "**Pasal 613 KUHPerdata:** penyerahan piutang atas nama dilakukan dengan akta otentik atau akta di bawah tangan, dan baru berlaku terhadap debitor (_cessus_) setelah diberitahukan kepadanya, atau disetujui atau diakui secara tertulis."),
  item("2.", "**Pasal 1533–1535 KUHPerdata:** penjualan piutang meliputi segala yang melekat padanya. Penjual hanya menanggung bahwa piutang itu ada pada saat diserahkan, bukan kemampuan debitor membayar, kecuali diperjanjikan lain."),
  item("3.", "**Pasal 612 KUHPerdata:** penyerahan benda bergerak dapat dilakukan dengan penyerahan kunci bangunan tempat benda itu berada. Penyerahan tidak diperlukan bila benda sudah dikuasai penerima."),
  item("4.", "**Pasal 1365 KUHPerdata:** dasar tuntutan terhadap pihak yang tanpa hak menguasai dan memanen kebun."),

  heading("IV.\tANALISIS YURIDIS"),
  sub("A. Bangunan dan benda: dijual, bukan dicessie"),
  item("1.", "_Cessie_ hanya berlaku untuk piutang (tagihan), bukan untuk benda. Kantor kebun, gudang, rumah karyawan, mesin, dan kendaraan adalah benda milik PT Rata Makmur, sehingga dialihkan melalui **jual beli**. Istilah \"cessie atas bangunan\" perlu dihindari dalam dokumen resmi agar tidak menimbulkan cacat bentuk."),
  item("2.", "Karena berlaku asas pemisahan horizontal, bangunan tetap milik Debitor dan masuk harta pailit (Pasal 21 UU 37/2004), meskipun berdiri di atas tanah negara. Bangunan ini tidak memiliki alas hak tanah yang dapat didaftarkan, sehingga peralihannya cukup dengan akta jual beli bangunan (sebaiknya akta notaris) dan berita acara serah terima."),
  item("3.", "**Catatan risiko:** Pasal 18 ayat (1) PP 40/1996 mewajibkan bekas pemegang hak membongkar bangunan. Artinya, pembeli sesungguhnya membeli bangunan beserta beban pembongkarannya, kecuali negara atau pemegang HGU baru memerlukan bangunan itu. Hal ini harus dinyatakan terbuka dalam dokumen penjualan (klausul _as is_), dan akan menekan harga."),
  sub("B. Hak atas ganti rugi: dapat dicessie, dengan catatan"),
  item("1.", "Hak atas ganti rugi menurut Pasal 18 ayat (2) dan Pasal 4 ayat (4) PP 40/1996 adalah tagihan yang bernilai uang. Tagihan semacam ini tergolong benda bergerak tidak berwujud (Pasal 511 KUHPerdata), sehingga termasuk harta pailit. Hak ini dapat dialihkan dengan _cessie_."),
  item("2.", "Hak ini bersifat **bersyarat dan belum tertentu**, karena tiga hal:"),
  item("a.", "baru timbul bila bangunan, tanaman, atau benda tersebut dinilai masih diperlukan untuk pengusahaan tanah;", 1),
  item("b.", "pihak yang wajib membayar (_cessus_) belum pasti, bisa negara atau pemegang HGU baru; dan", 1),
  item("c.", "besaran dan bentuk ganti rugi menurut Pasal 18 ayat (2) PP 40/1996 seharusnya diatur dengan Keputusan Presiden, yang sejauh penelusuran kami belum ada, sehingga dalam praktik ditetapkan melalui penilaian dan kesepakatan.", 1),
  item("3.", "Doktrin dan praktik mengakui _cessie_ atas piutang yang akan ada, sepanjang hubungan hukum yang melahirkannya sudah ada dan objeknya dapat ditentukan. Di sini dasar hukumnya sudah ada (PP 40/1996) dan objeknya dapat ditentukan melalui inventarisasi dan penilaian. Namun, karena _cessus_ belum pasti, _cessie_ ini paling aman bila **cessionaris-nya adalah pemohon HGU baru itu sendiri**. Dengan begitu, penerima hak dan pihak yang kelak wajib membayar ganti rugi berada di tangan yang sama, dan sengketa pembayaran tidak akan timbul."),
  item("4.", "Karena Kurator hanya menanggung adanya piutang (Pasal 1534 KUHPerdata), akta _cessie_ harus memuat klausul bahwa Kurator tidak menjamin besaran ganti rugi, tidak menjamin negara akan memberikan HGU kepada cessionaris, dan tidak menjamin penguasaan fisik atas kebun."),
  sub("C. Hak menagih hasil kebun sejak 10 April 2023"),
  item("1.", "Hasil panen atau uang kontrak yang diterima Debitor sejak putusan pailit termasuk harta pailit (Pasal 21 UU 37/2004), karena Debitor sudah tidak berwenang mengurus kekayaannya (Pasal 24 ayat (1))."),
  item("2.", "Terhadap pihak ketiga yang memanen berdasarkan kontrak dengan Debitor setelah 10 April 2023, kontrak itu tidak mengikat harta pailit. Kurator dapat menagih melalui gugatan lain-lain ke Pengadilan Niaga (Pasal 3 ayat (1) UU 37/2004 beserta Penjelasannya) atas dasar perbuatan melawan hukum (Pasal 1365 KUHPerdata)."),
  item("3.", "**Catatan risiko:** tanaman berdiri di atas tanah negara, dan Pasal 18 ayat (1) PP 40/1996 mewajibkan penyerahan tanaman kepada negara. Pihak lawan dapat membantah bahwa hasil panen bukan milik Debitor. Kurator tetap dapat berargumen bahwa selama negara belum mengambil alih, penanam dan pengusaha kebun adalah PT Rata Makmur. Tetapi karena ada ketidakpastian ini, hak tagih ini lebih realistis dijual (_cessie_) dengan harga diskon kepada pembeli paket yang bersedia menanggung risiko penagihannya, daripada ditagih sendiri dengan biaya perkara."),
  sub("D. Hak yang tidak dapat atau tidak layak dicessie"),
  item("1.", "**Gugatan pembatalan perbuatan Debitor (actio pauliana) atas pembagian aset 2021.** Pasal 47 UU 37/2004 menetapkan gugatan ini diajukan oleh Kurator. Kewenangan ini melekat pada jabatan Kurator demi kepentingan seluruh kreditor, sehingga tidak dapat dialihkan kepada pihak lain."),
  item("2.", "**Tuntutan tanggung jawab direksi (Pasal 104 ayat (2) UU 40/2007).** Tuntutan ini lebih tepat dijalankan Kurator sendiri atau diselesaikan melalui perdamaian dengan persetujuan Hakim Pengawas, misalnya dengan komitmen pribadi Agam Singarimbun untuk melunasi. Mengalihkannya kepada pihak ketiga berisiko dipandang merugikan kreditor."),
  item("3.", "**Kedudukan prioritas bekas pemegang hak (Pasal 22 PP 18/2021).** Kedudukan ini adalah pertimbangan kewenangan Menteri, bukan piutang, sehingga tidak dapat dicessie. Yang dapat dilakukan Kurator dengan izin Hakim Pengawas adalah membuat **surat pernyataan pelepasan kedudukan prioritas** kepada negara, sebagai bagian dari paket penjualan, agar pemohon HGU baru tidak terhalang."),
  sub("E. Jalur penjualan: lelang atau di bawah tangan"),
  item("1.", "Untuk **bangunan dan benda**, Pasal 185 ayat (1) mengharuskan penjualan di muka umum (lelang melalui KPKNL). Penjualan di bawah tangan baru dapat dilakukan setelah lelang tidak tercapai, dengan izin Hakim Pengawas (Pasal 185 ayat (2))."),
  item("2.", "Untuk **hak tagih yang bersyarat**, lebih tepat menggunakan Pasal 185 ayat (3), yaitu benda yang tidak segera atau sama sekali tidak dapat dibereskan: Kurator memutuskan tindakannya dengan izin Hakim Pengawas. Hak ini tidak memiliki pasar lelang yang wajar, sehingga cessie di bawah tangan dengan izin Hakim Pengawas adalah jalur yang sah."),
  item("3.", "**Rekomendasi:** mohon satu penetapan Hakim Pengawas yang mengizinkan penjualan paket (bangunan, benda, hak ganti rugi, hak tagih hasil kebun, dan pelepasan prioritas) secara di bawah tangan. Dasarnya Pasal 185 ayat (3), dengan alasan objeknya tidak dapat dilelang secara terpisah tanpa kehilangan nilai. Untuk menjaga harga terbaik dan independensi (Pasal 15 ayat (3)), Kurator sebaiknya mengumumkan penawaran terbuka kepada semua peminat terlebih dahulu, bukan hanya menunggu PT Raya Padang Langkat."),
  item("4.", "Kurator juga perlu memeriksa apakah calon pembeli terafiliasi dengan Debitor, direksi, atau pihak yang selama ini memanen kebun. Penjualan kepada pihak terafiliasi dengan harga di bawah nilai wajar dapat digugat kreditor dan menimbulkan tanggung jawab Kurator (Pasal 72)."),

  heading("V.\tLANGKAH-LANGKAH PELAKSANAAN"),
  grid(["No", "Langkah", "Dasar hukum", "Bisa tanpa Kurator ke lokasi?"], [
    R("1", "Minta sikap tertulis tim khusus Kanwil BPN Sumut: status tanah, apakah bangunan/tanaman diperlukan, siapa pemohon hak baru, dan kewajiban ganti rugi pemohon", "Pasal 18 dan 4 ayat (4) PP 40/1996; Pasal 22 PP 18/2021", "Ya (surat dan rapat di Medan)"),
    R("2", "Mohon penyegelan bangunan dan benda melalui Hakim Pengawas, dilaksanakan juru sita dengan saksi pemerintah daerah", "Pasal 99 UU 37/2004", "Ya, dilaksanakan juru sita dengan pengawalan Polri"),
    R("3", "Inventarisasi: daftar bangunan, mesin, kendaraan, jumlah dan umur pokok sawit; overlay batas bidang dengan citra satelit; selesaikan selisih luas 338 dan 388 Ha", "Pasal 98 UU 37/2004", "Sebagian besar ya (surveyor BPN, citra satelit, data Dinas Perkebunan, KJPP)"),
    R("4", "Penilaian KJPP: nilai bangunan dan benda (termasuk nilai sisa bila dibongkar), nilai ganti rugi tanaman, dan nilai hak tagih hasil kebun", "Praktik penilaian untuk harga wajar; PMK 122/2023 untuk lelang", "Ya, penilai turun dengan pengawalan"),
    R("5", "Somasi dan perintah penyerahan hasil kebun kepada Debitor dan pengontrak panen; minta daftar kontrak dan penerimaan sejak 10 April 2023", "Pasal 21, 24, 110 UU 37/2004", "Ya (surat)"),
    R("6", "Penawaran terbuka kepada peminat (pengumuman di surat kabar dan surat kepada peminat yang diketahui); uji afiliasi calon pembeli", "Pasal 15 ayat (3) dan 72 UU 37/2004", "Ya"),
    R("7", "Mohon penetapan Hakim Pengawas: izin penjualan paket di bawah tangan, nilai minimum, dan pelepasan prioritas", "Pasal 185 ayat (3) UU 37/2004", "Ya"),
    R("8", "Penandatanganan akta notaris: jual beli bangunan dan benda, cessie hak ganti rugi dan hak tagih hasil kebun, pernyataan pelepasan prioritas; seluruhnya _as is_", "Pasal 613, 1533–1535 KUHPerdata", "Ya (di kantor notaris)"),
    R("9", "Pembayaran lunas ke rekening harta pailit sebelum atau bersamaan dengan penandatanganan akta", "Pasal 69 UU 37/2004", "Ya"),
    R("10", "Pemberitahuan cessie (betekening) kepada cessus: Kanwil BPN Sumut, Kantah Langkat, Debitor, dan pengontrak panen", "Pasal 613 ayat (2) KUHPerdata", "Ya (surat tercatat)"),
    R("11", "Penyerahan yuridis: penyerahan kunci dan dokumen di kantor, berita acara serah terima; penguasaan fisik menjadi urusan pembeli", "Pasal 612 KUHPerdata", "Ya"),
    R("12", "Pencabutan blokir di Kantah Langkat bila diminta, laporan kepada Hakim Pengawas, dan pencantuman hasil penjualan dalam daftar pembagian", "Pasal 189 UU 37/2004", "Ya"),
  ], [450, 3650, 2550, 2376], ["C", "L", "L", "L"]),
  blank(),

  heading("VI.\tPENGAMANAN DARI GANGGUAN OKNUM PREMAN"),
  sub("A. Prinsip"),
  item("1.", "**Kurator tidak menghadapi gangguan sendirian.** Pengamanan harta pailit adalah kegiatan resmi negara. Setiap kegiatan lapangan harus berbentuk kegiatan pejabat yang berwenang (juru sita, surveyor BPN, penilai) dengan pengawalan Polri."),
  item("2.", "**Tidak ada negosiasi dan tidak ada pembayaran kepada oknum di lapangan.** Pembayaran \"uang keamanan\" dapat menjadi pungutan liar atau gratifikasi, dan tidak dapat dipertanggungjawabkan sebagai biaya kepailitan."),
  item("3.", "**Pindahkan risiko melalui struktur penjualan.** Dengan penjualan _as is_ dan penyerahan yuridis, penguasaan fisik kebun menjadi urusan pembeli, yang biasanya lebih siap menghadapi keadaan lapangan dan telah memperhitungkannya dalam harga."),
  sub("B. Langkah persiapan"),
  item("1.", "Surati **Kapolres Langkat** untuk memohon bantuan pengamanan kegiatan, dengan tembusan Kapolda Sumatera Utara, Kapolsek Selesai, dan Hakim Pengawas. Lampirkan putusan pailit, penetapan Hakim Pengawas, dan surat tugas. Dasarnya adalah tugas Polri memelihara keamanan dan ketertiban serta memberikan perlindungan kepada masyarakat (Pasal 13 dan 14 UU 2/2002)."),
  item("2.", "Koordinasikan dengan **Camat Selesai, Kepala Desa Sei Tampa dan Bekulap, Bhabinkamtibmas, dan Babinsa** untuk mengetahui siapa yang menguasai kebun dan siapa yang berpotensi mengganggu, sebelum ada yang turun."),
  item("3.", "Lakukan **pemetaan jarak jauh terlebih dahulu**: citra satelit, data Dinas Perkebunan dan Peternakan Provinsi Sumatera Utara, dan informasi pemerintah desa. Tujuannya agar kunjungan lapangan singkat dan terarah."),
  item("4.", "Bila ada oknum yang mengaku berhak, undang mereka ke **tempat netral** (kantor camat, Polsek, atau kantor BHP), bukan ditemui di kebun."),
  sub("C. Protokol pada hari kegiatan"),
  item("1.", "Tim paling sedikit 4 (empat) orang dengan surat tugas, didampingi juru sita atau surveyor BPN, dan dikawal Polri. Kegiatan dilakukan pada siang hari, dengan titik kumpul di Polsek."),
  item("2.", "Seluruh kegiatan didokumentasikan (foto dan video dengan penanda waktu dan lokasi), dan dituangkan dalam berita acara yang ditandatangani pejabat yang hadir."),
  item("3.", "Tidak membawa uang tunai dan tidak menandatangani apa pun di lokasi selain berita acara resmi."),
  item("4.", "Bila terjadi penghadangan atau ancaman: jangan berdebat, catat identitas dan kendaraan pelaku bila aman, tinggalkan lokasi bersama pengawal, lalu buat laporan polisi dan laporkan kepada Hakim Pengawas pada hari yang sama."),
  sub("D. Upaya hukum terhadap gangguan"),
  item("1.", "Tindakan menghalangi pejabat, pemerasan, ancaman kekerasan, perusakan, dan menarik atau menyembunyikan barang yang berada dalam sita dapat dilaporkan sebagai tindak pidana menurut KUHP (UU 1/2023, berlaku sejak 2 Januari 2026). Di KUHP lama, perbuatan ini diatur antara lain dalam Pasal 212, 231, 368, dan 406. **Nomor pasal padanannya dalam KUHP baru perlu dicocokkan sebelum dikutip dalam laporan resmi.**"),
  item("2.", "Bila gangguan digerakkan atau dibiarkan oleh Debitor, Kurator dapat meminta Hakim Pengawas mengusulkan penahanan Debitor karena tidak bekerja sama (Pasal 93 UU 37/2004), serta menggugat penyerahan hasil kebun melalui gugatan lain-lain."),

  heading("VII.\tAPAKAH KURATOR HARUS TURUN KE LOKASI?"),
  item("1.", "**Tidak ada ketentuan yang mewajibkan Kurator pribadi hadir di setiap kegiatan lapangan.** Kurator bertugas mengurus dan membereskan (Pasal 69 UU 37/2004) dan dapat menggunakan jasa pihak lain yang biayanya dibebankan sebagai biaya kepailitan: juru sita untuk penyegelan (Pasal 99), surveyor BPN untuk pengukuran, KJPP untuk penilaian, dan notaris untuk akta."),
  item("2.", "**Tanggung jawab tidak ikut berpindah.** Kurator tetap bertanggung jawab atas kebenaran inventarisasi dan kewajaran harga (Pasal 72). Karena itu, setiap laporan pihak lain harus berupa berita acara atau laporan resmi yang ditandatangani, disertai dokumentasi."),
  item("3.", "**Yang dapat dilakukan tanpa ke lokasi:** korespondensi dengan BPN, Debitor, dan pengontrak; rapat di Medan; pemetaan jarak jauh; penawaran terbuka; permohonan penetapan; penandatanganan akta; pembayaran; dan penyerahan yuridis (Pasal 612 KUHPerdata)."),
  item("4.", "**Yang sebaiknya tetap dihadiri Kurator, dengan pengawalan:** satu kali kegiatan resmi di lokasi, yaitu penyegelan atau inventarisasi bersama juru sita, BPN, dan KJPP. Kehadiran ini menjadi bukti kehati-hatian bila kelak ada gugatan dari kreditor atau pembeli. Bila keadaan keamanan tidak memungkinkan menurut penilaian Polri, ketidakhadiran itu dicatat dalam berita acara dan dilaporkan kepada Hakim Pengawas."),

  heading("VIII.\tREKOMENDASI"),
  item("1.", "Tempuh model **penjualan paket apa adanya (as is) kepada pemohon HGU baru** melalui penawaran terbuka dan penetapan Hakim Pengawas (Pasal 185 ayat (3)). Dengan model ini, hak ganti rugi dan kewajiban membayarnya berada pada pihak yang sama, dan risiko lapangan berpindah kepada pembeli."),
  item("2.", "Jangan mengalihkan kewenangan _actio pauliana_ dan tuntutan tanggung jawab direksi; jalankan sendiri atau selesaikan dengan persetujuan Hakim Pengawas."),
  item("3.", "Minta sikap tertulis Kanwil BPN Sumut sebelum menetapkan harga, karena nilai hak ganti rugi sepenuhnya bergantung pada apakah bangunan dan tanaman dinilai masih diperlukan."),
  item("4.", "Ajukan permohonan pengamanan kepada Polres Langkat dan penyegelan melalui Hakim Pengawas sebelum ada kegiatan lapangan apa pun."),
  item("5.", "Sebelum dipakai dalam dokumen resmi, cocokkan: (a) ketentuan PP 18/2021 tentang kewajiban bekas pemegang HGU dan tenggat pembongkarannya; (b) ada tidaknya Keputusan Presiden tentang ganti rugi menurut Pasal 18 ayat (2) PP 40/1996; dan (c) nomor pasal padanan dalam KUHP baru."),
  blank(),
  sign(
    ["Mengetahui,", "Kepala Seksi Harta Peninggalan Wilayah II,", "", "", "", "**Elsintha Damayanti**"],
    ["Medan, 29 September 2026", "Tim Kurator PT Rata Makmur,", "Kurator Keperdataan Ahli Pertama,", "", "", "", "**Shela Natasha**"],
  ),
];

const doc = new Document({
  creator: "Tim Kurator BHP Medan",
  title: "Kajian Cessie dan Pengamanan Lapangan",
  styles: { default: { document: { run: { font: FONT, size: SIZE } } } },
  sections: [{
    properties: { page: { size: { width: 11906, height: 16838 }, margin: { top: 1134, bottom: 1134, left: 1440, right: 1440 } } },
    footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [
      new TextRun({ children: ["Halaman ", PageNumber.CURRENT, " dari ", PageNumber.TOTAL_PAGES], font: FONT, size: 16, color: "808080" })] })] }) },
    children: kajian,
  }],
});
Packer.toBuffer(doc).then(b => { fs.writeFileSync(process.argv[2] || "kajian.docx", b); console.log("wrote"); });
