// ============================ SIMULASI KEGIATAN ============================
const L = ["L", "L", "L", "L", "L", "L"];
const sim = [
  ...kop(),
  center("**SIMULASI KEGIATAN**", { run: { size: 26 } }),
  center("**PEMBERESAN HAK KEPERDATAAN EKS HGU NO. 2/SEI TAMPA**"),
  center("**DAN PENYELESAIAN KEPAILITAN PT RATA MAKMUR (DALAM PAILIT)**", { after: 120 }),
  center("Lampiran Kajian Yuridis Cessie dan Pengamanan Lapangan, 29 September 2026", { after: 240 }),

  heading("I.\tTUJUAN DAN ASUMSI"),
  body("Simulasi ini menggambarkan jalannya kegiatan dari awal sampai kepailitan dapat diakhiri: siapa melakukan apa, kapan, di mana, dokumen apa yang dihasilkan, dan apa yang dilakukan bila terjadi hambatan. Tanggal bersifat perkiraan dan dapat digeser sesuai jadwal Hakim Pengawas dan instansi terkait."),
  body("Asumsi yang dipakai:"),
  item("1.", "Kegiatan dimulai Kamis, 1 Oktober 2026, setelah Telaahan Staf disetujui Kepala Balai."),
  item("2.", "Seluruh kegiatan lapangan dipadatkan menjadi **satu hari operasi gabungan** (penyegelan, inventarisasi, pengukuran, dan penilaian sekaligus), agar Kurator dan tim cukup turun satu kali."),
  item("3.", "Model pemberesan yang dipakai adalah penjualan paket apa adanya (as is) kepada pemohon HGU baru, sesuai rekomendasi Kajian Yuridis."),
  item("4.", "Berjalan paralel dengan jalur pembayaran oleh Debitor. Bila Debitor melunasi, pemberesan paket tetap berjalan untuk hak yang tersisa, atau dihentikan bila seluruh tagihan dan biaya sudah lunas."),

  heading("II.\tPEMBAGIAN PERAN (USULAN)"),
  body("Nama petugas disesuaikan dengan Keputusan Kepala Balai Nomor W.2.AHU.AHU.1-AH.06.06-2929 Tahun 2026. Satu orang dapat memegang lebih dari satu peran."),
  grid(["Peran", "Tugas pokok", "Diisi oleh"], [
    R("Penanggung jawab", "Menandatangani surat keluar, memimpin rapat dengan instansi", "Kepala Balai"),
    R("Ketua Tim", "Mengendalikan jadwal, mengambil keputusan di lapangan, juru bicara tunggal", "Kurator Ahli Madya"),
    R("Koordinator Hukum", "Menyusun konsep surat, permohonan penetapan, akta, dan daftar pembagian", "Kurator Ahli Muda"),
    R("Penghubung Instansi", "Kontak tetap dengan BPN, Polres, KPP, pemda, dan notaris", "Kurator Ahli Pertama"),
    R("Koordinator Lapangan", "Logistik, titik kumpul, komunikasi dengan pengawal, keputusan evakuasi", "Kurator Ahli Pertama"),
    R("Notulis dan Dokumentasi", "Berita acara, foto dan video, daftar hadir, arsip digital", "Kurator Ahli Pertama"),
    R("Pengelola Keuangan Boedel", "Rekening harta pailit, bukti setor, perhitungan pembagian", "Kurator Ahli Pertama bersama Bendahara"),
    R("Pengawas", "Menerima laporan, memberi arahan, menyetujui langkah", "Kasi Harta Peninggalan Wilayah II"),
  ], [2300, 4526, 2200], L),
  blank(),

  heading("III.\tJADWAL KEGIATAN PER FASE"),
  grid(["Fase / Waktu", "Kegiatan", "Pelaksana", "Keluaran"], [
    RB("Fase 0: Persiapan internal", "", "", ""),
    R("1–2 Okt 2026", "Rapat tim: pembagian peran, pengesahan Telaahan Staf dan Kajian, pembukaan berkas kerja bersama", "Seluruh tim", "Notula rapat; daftar tugas"),
    R("2 Okt 2026", "Surat tanggapan kepada Debitor (tenggat proposal 14 hari kerja, jatuh 22 Okt 2026)", "Koordinator Hukum; ditandatangani Kepala", "Surat tanggapan; tanda terima"),
    RB("Fase 1: Koordinasi dan dasar hukum", "", "", ""),
    R("5 Okt 2026", "Laporan hasil rapat 14 Sept kepada Hakim Pengawas, sekaligus permohonan penyegelan (Pasal 99) dan arahan penghentian lelang tanah", "Ketua Tim; Koordinator Hukum", "Surat laporan dan permohonan"),
    R("5 Okt 2026", "Surat kepada Kanwil BPN Sumut (tim khusus): status tanah, kebutuhan bangunan/tanaman, pemohon hak baru, kewajiban ganti rugi", "Penghubung Instansi", "Surat keluar"),
    R("5 Okt 2026", "Surat kepada KPP Pratama Binjai dan Medan Polonia: konfirmasi posisi tagihan dan unit penerbit pernyataan lunas", "Penghubung Instansi", "Surat keluar"),
    R("6 Okt 2026", "Surat permohonan bantuan pengamanan kepada Kapolres Langkat, tembusan Kapolda, Kapolsek Selesai, Hakim Pengawas", "Penghubung Instansi", "Surat keluar"),
    R("7–9 Okt 2026", "Permintaan penawaran jasa KJPP (paling sedikit 3 KJPP) dan pemilihan penilai", "Koordinator Hukum", "Surat permintaan; berita acara pemilihan"),
    R("12–16 Okt 2026", "Rapat koordinasi di Kanwil BPN Sumut (Medan) bersama Kantah Langkat; rapat koordinasi pengamanan di Polres Langkat", "Ketua Tim; Penghubung Instansi", "Notula; kesepakatan tanggal operasi"),
    R("± 19 Okt 2026", "Penetapan Hakim Pengawas tentang penyegelan dan pengangkatan penilai", "Hakim Pengawas", "Penetapan"),
    RB("Fase 2: Pemetaan jarak jauh", "", "", ""),
    R("12–23 Okt 2026", "Overlay batas bidang dengan citra satelit; permintaan data luas tanam dan produksi ke Dinas Perkebunan; penggalian informasi dari Camat Selesai, Kepala Desa, Bhabinkamtibmas, dan Babinsa", "Koordinator Lapangan; Penghubung Instansi", "Peta kerja; daftar bangunan awal; peta potensi gangguan"),
    R("22 Okt 2026", "Batas akhir proposal pembayaran Debitor (lihat Bagian VI)", "Pengelola Keuangan Boedel", "Catatan diterima atau tidak"),
    RB("Fase 3: Operasi lapangan gabungan", "", "", ""),
    R("26–30 Okt 2026", "Gladi di kantor: pembagian tim, pemeriksaan logistik, simulasi skenario kontinjensi (Bagian V)", "Seluruh tim; perwakilan Polres bila bersedia", "Daftar periksa; rencana evakuasi"),
    R("Selasa, 3 Nov 2026", "Operasi gabungan satu hari: penyegelan oleh juru sita, inventarisasi, pengukuran oleh surveyor BPN, peninjauan KJPP (rundown pada Bagian IV)", "Tim, juru sita, BPN, KJPP, Polri, pemerintah desa", "Berita acara penyegelan; berita acara inventarisasi; dokumentasi"),
    RB("Fase 4: Penilaian dan pengamanan hasil", "", "", ""),
    R("4 Nov – 4 Des 2026", "KJPP menyusun laporan penilaian: bangunan dan benda (termasuk nilai sisa bila dibongkar), ganti rugi tanaman, hak tagih hasil kebun", "KJPP; Koordinator Hukum", "Laporan penilaian"),
    R("4–13 Nov 2026", "Somasi kepada Debitor dan pengontrak panen untuk menyerahkan hasil kebun sejak 10 April 2023 beserta kontraknya", "Koordinator Hukum", "Somasi; tanda terima"),
    RB("Fase 5: Penawaran terbuka", "", "", ""),
    R("7 Des 2026", "Pengumuman penawaran paket di surat kabar dan surat kepada peminat yang diketahui (termasuk PT Raya Padang Langkat)", "Koordinator Hukum", "Pengumuman; surat undangan"),
    R("14 Des 2026", "Penjelasan (aanwijzing) di kantor BHP Medan: objek, status hukum as is, syarat peserta, jadwal", "Ketua Tim", "Berita acara penjelasan"),
    R("7 Jan 2027", "Batas akhir penawaran tertutup, disertai pernyataan tidak terafiliasi dan bukti kemampuan dana", "Koordinator Hukum", "Dokumen penawaran"),
    R("8 Jan 2027", "Pembukaan penawaran di hadapan saksi; evaluasi dan penetapan penawar terbaik", "Ketua Tim; saksi", "Berita acara pembukaan dan evaluasi"),
    RB("Fase 6: Penetapan Hakim Pengawas", "", "", ""),
    R("11 Jan 2027", "Permohonan izin penjualan paket di bawah tangan (Pasal 185 ayat (3)) serta pernyataan pelepasan prioritas", "Koordinator Hukum", "Surat permohonan"),
    R("± 25 Jan 2027", "Penetapan Hakim Pengawas", "Hakim Pengawas", "Penetapan izin penjualan"),
    RB("Fase 7: Akta, pembayaran, dan pemberitahuan", "", "", ""),
    R("± 1 Feb 2027", "Pembayaran lunas ke rekening harta pailit; penandatanganan akta notaris (jual beli bangunan dan benda, cessie, pelepasan prioritas)", "Kepala/Ketua Tim; pembeli; notaris", "Bukti setor; akta"),
    R("± 3 Feb 2027", "Pemberitahuan cessie kepada Kanwil BPN Sumut, Kantah Langkat, Debitor, pengontrak panen; penyerahan kunci dan dokumen di kantor", "Penghubung Instansi", "Surat pemberitahuan; berita acara serah terima"),
    RB("Fase 8: Pembagian dan pengakhiran", "", "", ""),
    R("Feb 2027", "Laporan kepada Hakim Pengawas; penyusunan daftar pembagian (Pasal 189); konsultasi urutan pembagian eks karyawan dan kreditor pajak", "Koordinator Hukum; Pengelola Keuangan", "Daftar pembagian"),
    R("Feb–Mar 2027", "Daftar pembagian disediakan untuk diperiksa kreditor dan diumumkan; masa perlawanan (Pasal 192–194)", "Koordinator Hukum", "Pengumuman; catatan perlawanan"),
    R("Mar 2027", "Pembayaran kepada kreditor; tanda terima lunas; laporan akhir; kepailitan berakhir (Pasal 202)", "Pengelola Keuangan; Ketua Tim", "Bukti bayar; laporan akhir"),
  ], [1650, 3700, 1900, 1776], L),
  blank(),

  heading("IV.\tRUNDOWN OPERASI LAPANGAN GABUNGAN (SELASA, 3 NOVEMBER 2026)"),
  sub("A. Susunan rombongan"),
  item("1.", "Tim Kurator 4–5 orang (Ketua Tim, Koordinator Lapangan, Notulis dan Dokumentasi, Penghubung Instansi)."),
  item("2.", "Juru sita Pengadilan Niaga dan dua saksi, salah satunya wakil pemerintah daerah (Camat atau Kepala Desa)."),
  item("3.", "Surveyor Kantor Pertanahan Kabupaten Langkat dan penilai KJPP."),
  item("4.", "Pengawalan Polres Langkat/Polsek Selesai, Bhabinkamtibmas, dan Babinsa."),
  sub("B. Rundown"),
  grid(["Waktu (WIB)", "Kegiatan", "Tempat", "Penanggung jawab"], [
    R("05.30", "Kumpul di BHP Medan; cek kehadiran, logistik, dan surat; doa", "BHP Medan", "Koordinator Lapangan"),
    R("06.00", "Berangkat (± 2 jam); komunikasi grup aktif; lokasi dibagikan ke kantor", "Perjalanan", "Koordinator Lapangan"),
    R("08.00", "Titik kumpul dan apel singkat bersama Polri, juru sita, BPN, KJPP, pemerintah desa; penjelasan tujuan dan batas kegiatan; penetapan jalur evakuasi dan kode batal", "Polsek Selesai", "Ketua Tim; perwira pengawal"),
    R("08.45", "Kunjungan ke kantor desa: pemberitahuan kegiatan, konfirmasi saksi, informasi terakhir kondisi kebun", "Kantor Desa", "Penghubung Instansi"),
    R("09.30", "Masuk lokasi bersama pengawal; pembacaan maksud kegiatan kepada orang yang ada di lokasi (naskah pada Bagian V.B)", "Gerbang kebun", "Ketua Tim (juru bicara tunggal)"),
    R("09.45–11.30", "Tim A: penyegelan bangunan dan benda oleh juru sita. Tim B: inventarisasi dan foto bangunan, mesin, kendaraan. Tim C: surveyor BPN mengambil titik koordinat batas dan bangunan", "Kantor kebun, gudang, emplasemen", "Juru sita; Notulis; Surveyor"),
    R("11.30–12.30", "Peninjauan KJPP pada sampel blok tanaman (umur, kerapatan, kondisi); pencatatan pihak yang sedang memanen, bila ada", "Blok sampel", "Penilai KJPP; Koordinator Lapangan"),
    R("12.30", "Batas waktu keluar dari lokasi. Kegiatan yang belum selesai dicatat dan tidak diperpanjang", "Lokasi", "Ketua Tim"),
    R("13.00", "Penandatanganan berita acara penyegelan dan inventarisasi oleh pejabat dan saksi; makan siang", "Polsek atau Kantor Camat", "Notulis"),
    R("14.00", "Kembali ke Medan; laporan singkat melalui pesan kepada Kasi dan Kepala", "Perjalanan", "Ketua Tim"),
    R("16.00", "Rapat evaluasi; unggah dokumentasi ke arsip; konsep laporan kepada Hakim Pengawas", "BHP Medan", "Seluruh tim"),
  ], [1250, 4300, 1750, 1726], L),
  blank(),
  sub("C. Daftar periksa perlengkapan"),
  item("1.", "Dokumen: salinan putusan pailit, penetapan Hakim Pengawas, surat tugas, surat balasan Polres, peta kerja, formulir berita acara kosong, daftar hadir."),
  item("2.", "Alat: kertas segel dan stempel, kamera dan ponsel dengan penanda lokasi, power bank, GPS, meteran, rompi identitas."),
  item("3.", "Keselamatan: nomor darurat Polsek dan Polres, kotak P3K, air minum, kendaraan dalam kondisi siap jalan dan diparkir menghadap keluar."),
  item("4.", "Larangan: membawa uang tunai berlebih, menandatangani dokumen selain berita acara resmi, dan berbicara kepada media di lokasi."),

  heading("V.\tSIMULASI SKENARIO KONTINJENSI"),
  sub("A. Tabel respons"),
  grid(["No", "Skenario", "Tanda awal", "Respons", "Dokumen"], [
    R("1", "Jalan masuk dihadang sekelompok orang", "Kendaraan diberhentikan, portal ditutup", "Rombongan berhenti. Hanya perwira pengawal dan Ketua Tim yang berbicara. Bila tidak dibuka dalam 15 menit, kegiatan dibatalkan dan rombongan kembali ke Polsek", "Berita acara penundaan; laporan polisi bila ada ancaman"),
    R("2", "Oknum mengaku pemilik atau ahli waris dan meminta uang", "Permintaan \"uang masuk\" atau \"uang keamanan\"", "Tolak dengan sopan. Undang yang bersangkutan membawa bukti ke kantor BHP atau Polsek. Catat identitas bila aman", "Catatan kejadian; foto; laporan kepada Hakim Pengawas"),
    R("3", "Pekerja atau pemanen menolak kegiatan", "Kerumunan, suara meninggi", "Juru bicara menjelaskan bahwa kegiatan hanya mendata dan menyegel, tidak mengusir siapa pun. Bila memanas, kegiatan dipersingkat ke titik yang aman", "Berita acara dengan catatan keadaan"),
    R("4", "Keluarga Debitor datang dan keberatan", "Kedatangan pihak Debitor atau kuasanya", "Tunjukkan putusan dan penetapan; sampaikan bahwa keberatan diajukan tertulis kepada Hakim Pengawas. Tidak berdebat di lokasi", "Catatan kejadian; surat kepada Debitor"),
    R("5", "Pengawal Polri batal hadir", "Pemberitahuan pagi hari", "Operasi ditunda. Kurator tidak masuk lokasi tanpa pengawalan. Jadwal ulang melalui Polres", "Berita acara penundaan"),
    R("6", "Bangunan terkunci atau barang sudah dipindahkan", "Temuan di lokasi", "Juru sita mencatat keadaan; tidak membuka paksa tanpa dasar. Kurator menyurati Debitor untuk menyerahkan kunci atau menjelaskan keberadaan barang", "Berita acara keadaan; somasi"),
    R("7", "Ancaman kekerasan atau ada anggota tim terluka", "Senjata, lemparan, dorongan", "Evakuasi segera bersama pengawal ke Polsek; pertolongan pertama; laporan polisi dan laporan kepada Kepala dan Hakim Pengawas pada hari yang sama", "Laporan polisi; visum bila perlu; kronologi"),
    R("8", "Hujan deras atau akses terputus", "Prakiraan cuaca, jalan licin", "Kegiatan dipersingkat ke bangunan utama; blok tanaman dijadwalkan ulang bersama KJPP saja", "Berita acara penundaan sebagian"),
  ], [450, 1800, 1700, 3300, 1776], ["C", "L", "L", "L", "L"]),
  blank(),
  sub("B. Naskah juru bicara di lokasi"),
  body("Disampaikan oleh Ketua Tim, dengan suara tenang, setelah pengawal berada di samping:"),
  p("_\"Selamat pagi, Bapak dan Ibu. Kami dari Balai Harta Peninggalan Medan, Kementerian Hukum, selaku Kurator PT Rata Makmur yang telah dinyatakan pailit oleh Pengadilan Niaga Medan. Hari ini kami bersama juru sita pengadilan, Kantor Pertanahan Langkat, dan kepolisian hanya melakukan pendataan dan penyegelan bangunan milik perusahaan. Kami tidak mengusir siapa pun dan tidak mengambil barang pribadi. Bila ada Bapak atau Ibu yang merasa berhak atas sesuatu di sini, silakan sampaikan secara tertulis ke kantor kami di Jalan Listrik No. 10 Medan, atau melalui Polsek Selesai. Terima kasih atas pengertiannya.\"_", { indent: { left: 567, right: 567 } }),
  body("Kalimat yang tidak diucapkan: janji apa pun tentang siapa yang akan mendapat tanah, besarnya ganti rugi, atau kompensasi kepada pihak yang hadir."),

  heading("VI.\tJALUR PARALEL: RESPONS DEBITOR"),
  grid(["Skenario", "Kondisi per 22 Okt 2026", "Tindakan Kurator"], [
    R("A. Proposal layak", "Jadwal, jumlah, tanggal lunas, bukti dana, dan komitmen Agam Singarimbun lengkap", "Mohon persetujuan Hakim Pengawas atas setoran bertahap ke rekening harta pailit. Operasi lapangan dan penawaran tetap berjalan, tetapi penandatanganan akta paket dapat ditunda bila setoran berjalan sesuai jadwal"),
    R("B. Proposal tidak lengkap", "Hanya pernyataan atau setoran awal tanpa jadwal", "Minta kelengkapan satu kali dengan tenggat 7 hari kerja. Setoran yang masuk diterima dan dicatat, tetapi seluruh fase pemberesan tetap berjalan"),
    R("C. Tidak ada tanggapan", "Tidak ada surat atau setoran", "Seluruh fase berjalan. Kurator menyiapkan permintaan keterangan tentang pembagian aset 2021 (Pasal 110) dan menilai tuntutan tanggung jawab direksi (Pasal 104 ayat (2) UU 40/2007)"),
    R("D. Lunas penuh", "Seluruh tagihan dan biaya kepailitan disetor", "Bayar kreditor, terbitkan tanda terima lunas, laporkan kepada Hakim Pengawas; kepailitan berakhir (Pasal 202) dan Debitor dapat mengajukan rehabilitasi (Pasal 215–216)"),
  ], [1900, 2900, 4226], L),
  blank(),

  heading("VII.\tILUSTRASI PEMBAGIAN HASIL"),
  body("**Angka berikut rekaan untuk latihan perhitungan, bukan perkiraan nilai.** Nilai sebenarnya menunggu laporan KJPP dan hasil penawaran."),
  grid(["Uraian", "Jumlah (Rp)", "Keterangan"], [
    R("Hasil penjualan paket (rekaan)", "1.000.000.000", "Contoh angka"),
    R("Dikurangi PNBP 7% dari DPT", "(100.301.019)", "Sebelum dikurangi bagian yang telah dipotong tahun 2025"),
    R("Dikurangi biaya kegiatan (rekaan)", "(75.000.000)", "Juru sita, KJPP, pengumuman, notaris, perjalanan"),
    RB("Tersedia untuk kreditor", "824.698.981", ""),
    R("Sisa tagihan 6 eks karyawan", "(139.653.168)", "Bila didahulukan sesuai Putusan MK 67/PUU-XI/2013; menunggu arahan Hakim Pengawas"),
    R("Tagihan KPP Pratama Binjai", "(685.045.813)", "Dari tagihan Rp1.108.581.903"),
    RB("Tagihan KPP Binjai yang belum terbayar", "423.536.090", "Tetap menjadi utang Debitor; dapat menjadi dasar tuntutan kepada direksi"),
  ], [3700, 2000, 3326], ["L", "R", "L"]),
  blank(),

  heading("VIII.\tDAFTAR DOKUMEN YANG DIHASILKAN"),
  grid(["No", "Dokumen", "Fase", "Penandatangan"], [
    R("1", "Surat tanggapan kepada Debitor", "0", "Kepala"),
    R("2", "Laporan dan permohonan penyegelan kepada Hakim Pengawas", "1", "Kepala"),
    R("3", "Surat kepada Kanwil BPN Sumut dan Kantah Langkat", "1", "Kepala"),
    R("4", "Surat kepada KPP Pratama Binjai dan Medan Polonia", "1", "Kepala"),
    R("5", "Surat permohonan bantuan pengamanan kepada Kapolres Langkat", "1", "Kepala"),
    R("6", "Surat permintaan penawaran KJPP dan berita acara pemilihan", "1", "Kepala; Tim"),
    R("7", "Surat tugas operasi lapangan", "3", "Kepala"),
    R("8", "Berita acara penyegelan", "3", "Juru sita; saksi"),
    R("9", "Berita acara inventarisasi dan dokumentasi", "3", "Tim; saksi"),
    R("10", "Somasi kepada Debitor dan pengontrak panen", "4", "Kepala"),
    R("11", "Pengumuman penawaran dan berita acara penjelasan", "5", "Kepala; Tim"),
    R("12", "Berita acara pembukaan dan evaluasi penawaran", "5", "Tim; saksi"),
    R("13", "Permohonan izin penjualan di bawah tangan dan pelepasan prioritas", "6", "Kepala"),
    R("14", "Akta jual beli bangunan dan benda, akta cessie, pernyataan pelepasan prioritas", "7", "Kepala; pembeli; notaris"),
    R("15", "Surat pemberitahuan cessie dan berita acara serah terima", "7", "Kepala"),
    R("16", "Daftar pembagian, pengumuman, tanda terima lunas, laporan akhir", "8", "Kepala; Hakim Pengawas"),
  ], [450, 5376, 900, 2300], ["C", "L", "C", "L"]),
  blank(),

  heading("IX.\tTITIK KEPUTUSAN"),
  body("Pada setiap titik berikut, Ketua Tim melapor kepada Kasi dan Kepala sebelum melanjutkan:"),
  item("1.", "**Sebelum operasi lapangan:** penetapan penyegelan sudah terbit dan Polres menyatakan kesediaan mengawal secara tertulis. Bila salah satu belum ada, operasi ditunda."),
  item("2.", "**Setelah sikap BPN diterima:** bila BPN menyatakan tanah akan ditata untuk Bank Tanah atau reforma agraria, penawaran paket diarahkan ke penagihan ganti rugi kepada negara, dan hak ganti rugi tidak dijual kepada pihak swasta."),
  item("3.", "**Setelah laporan KJPP:** bila nilai bersih paket lebih kecil dari biaya pemberesan, Kurator mengusulkan pengakhiran kepailitan kepada Hakim Pengawas."),
  item("4.", "**Setelah pembukaan penawaran:** bila tidak ada penawar, atau penawar terafiliasi dengan Debitor dengan harga di bawah nilai KJPP, penawaran diulang satu kali sebelum menempuh langkah lain."),
  blank(),
  sign(
    ["Mengetahui,", "Kepala Seksi Harta Peninggalan Wilayah II,", "", "", "", "**Elsintha Damayanti**"],
    ["Medan, 29 September 2026", "Tim Kurator PT Rata Makmur,", "Kurator Keperdataan Ahli Pertama,", "", "", "", "**Shela Natasha**"],
  ),
];

const doc = new Document({
  creator: "Tim Kurator BHP Medan",
  title: "Simulasi Kegiatan PT Rata Makmur",
  styles: { default: { document: { run: { font: FONT, size: SIZE } } } },
  sections: [{
    properties: { page: { size: { width: 11906, height: 16838 }, margin: { top: 1134, bottom: 1134, left: 1440, right: 1440 } } },
    footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [
      new TextRun({ children: ["Halaman ", PageNumber.CURRENT, " dari ", PageNumber.TOTAL_PAGES], font: FONT, size: 16, color: "808080" })] })] }) },
    children: sim,
  }],
});
Packer.toBuffer(doc).then(b => { fs.writeFileSync(process.argv[2] || "simulasi.docx", b); console.log("wrote"); });
